//
//  HomeScenePresenter.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScenePresentationLogic {
    func presentItem(response: HomeScene.GetResponse.Response)
}

class HomeScenePresenter: HomeScenePresentationLogic {
  
  weak var viewController: HomeSceneDisplayLogic?
  
  // MARK: Do something
    func presentItem(response: HomeScene.GetResponse.Response) {
        let viewModel = response.items
      
        viewController?.displayData(viewModel: HomeScene.GetResponse.ViewModel(data: viewModel))
    }
    
//  func presentSomething(response: HomeScene.Something.Response) {
//    let viewModel = HomeScene.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
