//
//  HomeSceneViewController.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSceneDisplayLogic: AnyObject {
  func displaySomething(viewModel: HomeScene.Something.ViewModel)
}

class HomeSceneViewController: UIViewController, HomeSceneDisplayLogic
{
  var interactor: HomeSceneBusinessLogic?
  var router: (HomeSceneRoutingLogic & HomeSceneDataPassing)?

  // MARK: Object lifecycle
 
    init(interactor: HomeSceneBusinessLogic, router: (HomeSceneRoutingLogic & HomeSceneDataPassing)) {
        self.interactor = interactor
        self.router = router
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
  }
  
  // MARK: Setup
  

  // MARK: Routing
  
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
      self.view.backgroundColor = .blue
    doSomething()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
  //  let request = HomeScene.Something.Request()
//    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: HomeScene.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}
