//
//  HomeSceneModels.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeScene {
  
    enum GetDetails {
        
        struct Request {
        }
        struct Response {
            let items: [Item]
        }
        struct ViewModel {
            let data: [Item]
        }
        struct Error {
        }
    }
}
