//
//  HomeSceneInteractor.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSceneBusinessLogic {
    func getData(request: HomeScene.GetDetails.Request)
}

protocol HomeSceneDataStore { }

final class HomeSceneInteractor:  HomeSceneDataStore {
    
    var presenter: HomeScenePresentationLogic
    var worker: HomeSceneWorker
    var fetchedItem = [Item]()
    
    init(presenter: HomeScenePresentationLogic, worker: HomeSceneWorker) {
        self.presenter = presenter
        self.worker = worker
    }
}

extension HomeSceneInteractor: HomeSceneBusinessLogic {
    
    func getData(request: HomeScene.GetDetails.Request) {
        Task {
            do {
                let mainResponse = try await worker.fetchData()
                DispatchQueue.main.async { [weak self] in
                    guard let self = self else { return}
                    self.fetchedItem = mainResponse.items
                    self.presenter.presentItem(response: HomeScene.GetDetails.Response(items:  self.fetchedItem))
                }
            } catch {
                presenter.presentError(error: HomeScene.GetDetails.Error())
            }
        }
    }
}
