//
//  HomeSceneRouter.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeSceneRoutingLogic {
    func routToErrorAnimation()
}

protocol HomeSceneDataPassing {
    var dataStore: HomeSceneDataStore { get }
}

final class HomeSceneRouter: NSObject, HomeSceneRoutingLogic, HomeSceneDataPassing {
    
    weak var viewController: HomeSceneViewController?
    var dataStore: HomeSceneDataStore
 
    init(dataStore: HomeSceneDataStore) {
        self.dataStore = dataStore
    }
    
    // MARK: Navigation
    func routToErrorAnimation() {
        DispatchQueue.main.async {[weak self] in
            let vc = LottieAnimatedScene()
            self?.viewController?.navigationController?.pushViewController(vc, animated: true)
        }
    }
}
