//
//  HomeSceneWorker.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeSceneWorkerLogic {
    func fetchData() async throws -> MainResponse
}

final class HomeSceneWorker {
    private let api: APIManager
    private let apiUrl = ApiUrl.mainURL.rawValue
    
    init(api: APIManager) {
        self.api = api
    }
}

extension HomeSceneWorker: HomeSceneWorkerLogic {
    func fetchData() async throws -> MainResponse {
        try await api.fetchData(urlString: apiUrl, decodingType: MainResponse.self)
    }
}
