//
//  HomeScenePresenter.swift
//  Trending
//
//  Created by Natia's Mac on 08.02.23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeScenePresentationLogic {
    func presentItem(response: HomeScene.GetDetails.Response)
    func presentError(error: HomeScene.GetDetails.Error)
}

final class HomeScenePresenter: HomeScenePresentationLogic {
    
    weak var viewController: HomeSceneDisplayLogic?
    
    func presentItem(response: HomeScene.GetDetails.Response) {
        let viewModel = response.items
        
        viewController?.displayData(viewModel: HomeScene.GetDetails.ViewModel(data: viewModel))
    }
    
    func presentError(error: HomeScene.GetDetails.Error) {
        viewController?.displayErrorMessage(error: HomeScene.GetDetails.Error())
    }
}
